version: '3'

services:
  apple_store:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: apple_store
    ports:
      - "5435:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - apple_store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: apple_store
      POSTGRES_HOST: apple_store
      POSTGRES_PORT: 5432
